### ISSUE TITLE
support.relative_path() not working on Windows

### ISSUE THREAD

**Issue by bastianeicher** [0install/0release#1]
Fails on Windows with:
```
Traceback (most recent call last):
  File "...\0release", line 77, in <module>
    import support
  File "...\support.py", line 226, in <module>
    assert relative_path('/foo', '/foo') == 'foo'
  File "...\support.py", line 223, in relative_path
    assert dst.startswith(stem)
AssertionError
```

**Comment by talex5** [comment]
Looks like you fixed this in 482f81ed4cf1f13c11dbd33bb1d663b543656a68 :-)
